// Generated by CoffeeScript 1.6.3
(function() {
  var aps, container, createArtPacks, dragleave, dragover, drop, showControls, showSounds, showTextures, urls;

  createArtPacks = require('./');

  urls = ['https://dl.dropboxusercontent.com/u/258156216/artpacks/ProgrammerArt-2.1-dev-ResourcePack-20140116.zip', 'invalid.zip', 'README.md'];

  container = document.createElement('div');

  container.style.position = 'absolute';

  container.style.height = '90%';

  container.style.width = '90%';

  container.style.border = '5px dotted black';

  document.body.appendChild(container);

  aps = createArtPacks(urls);

  aps.on('loadedURL', function(url) {
    return console.log('Loaded ', url);
  });

  showTextures = function(aps) {
    var img, name, url, _i, _len, _ref, _results;
    _ref = ['dirt', 'blocks/dirt', 'i/stick', 'items/stick', 'misc/shadow', 'minecraft:dirt', 'invalid'];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      name = _ref[_i];
      container.appendChild(document.createTextNode(name + ' = '));
      url = aps.getTexture(name);
      if (url == null) {
        container.appendChild(document.createTextNode('(not found)'));
      } else {
        img = document.createElement('img');
        img.src = url;
        img.title = name;
        container.appendChild(img);
      }
      _results.push(container.appendChild(document.createElement('br')));
    }
    return _results;
  };

  showSounds = function(aps) {
    var audio, name, url, _i, _len, _ref, _results;
    _ref = ['liquid/splash'];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      name = _ref[_i];
      container.appendChild(document.createTextNode('sound: ' + name + ' = '));
      url = aps.getSound(name);
      if (url == null) {
        container.appendChild(document.createTextNode('(not found)'));
      } else {
        console.log(url);
        audio = document.createElement('audio');
        audio.src = url;
        audio.controls = true;
        audio.title = name;
        container.appendChild(audio);
      }
      _results.push(container.appendChild(document.createElement('br')));
    }
    return _results;
  };

  showControls = function() {
    var audio, img, input;
    input = document.createElement('input');
    input.setAttribute('id', 'input');
    container.appendChild(input);
    img = document.createElement('img');
    img.setAttribute('id', 'outputImg');
    img.style.visibility = 'hidden';
    container.appendChild(img);
    audio = document.createElement('audio');
    audio.setAttribute('id', 'outputAudio');
    audio.controls = true;
    audio.style.visibility = 'hidden';
    container.appendChild(audio);
    return document.body.addEventListener('keyup', function(ev) {
      var url;
      url = aps.getTexture(input.value);
      console.log("lookup " + input.value + " = " + url);
      if (url != null) {
        img.src = url;
        return img.style.visibility = '';
      } else {
        img.style.visibility = 'hidden';
        url = aps.getSound(input.value);
        if (url != null) {
          audio.src = url;
          return audio.style.visibility = '';
        } else {
          return audio.style.visibility = 'hidden';
        }
      }
    });
  };

  aps.on('loadedAll', function(packs) {
    console.log(aps);
    while (container.firstChild) {
      container.removeChild(container.firstChild);
    }
    showTextures(aps);
    showSounds(aps);
    return showControls();
  });

  dragover = function(ev) {
    ev.stopPropagation();
    ev.preventDefault();
    return container.style.border = '5px dashed black';
  };

  dragleave = function(ev) {
    ev.stopPropagation();
    ev.preventDefault();
    return container.style.border = '5px dotted black';
  };

  drop = function(mouseEvent) {
    var file, files, reader, _i, _len, _results;
    dragleave(mouseEvent);
    files = mouseEvent.target.files || mouseEvent.dataTransfer.files;
    console.log('Dropped', files);
    _results = [];
    for (_i = 0, _len = files.length; _i < _len; _i++) {
      file = files[_i];
      console.log('Reading dropped', file);
      reader = new FileReader();
      reader.addEventListener('load', function(readEvent) {
        var arrayBuffer;
        if (readEvent.total !== readEvent.loaded) {
          return;
        }
        arrayBuffer = readEvent.currentTarget.result;
        if (!mouseEvent.shiftKey) {
          aps.clear();
        }
        return aps.addPack(arrayBuffer);
      });
      _results.push(reader.readAsArrayBuffer(file));
    }
    return _results;
  };

  container.addEventListener('dragover', dragover, false);

  container.addEventListener('dragleave', dragleave, false);

  container.addEventListener('drop', drop, false);

}).call(this);
